# Generated by Django 3.2 on 2022-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
